"""add session model

Revision ID: d96ab0ec7e4c
Revises: e18f9295cf25
Create Date: 2026-01-27 11:47:04.952046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd96ab0ec7e4c'
down_revision = 'e18f9295cf25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_session_date'), ['session_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_session_session_date'))
        batch_op.drop_index(batch_op.f('ix_session_activity_id'))

    op.drop_table('session')
    # ### end Alembic commands ###
